force-app/main/default/objects/Account/fields/CA_Email__c.field-meta.xml
<CustomField>
    <fullName>CA_Email__c</fullName>
    <description>E-mail Principal</description>
    <label>E-mail</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/CA_Telefone__c.field-meta.xml
<CustomField>
    <fullName>CA_Telefone__c</fullName>
    <description>Lista  - DDD (I) + TELEFONE</description>
    <label>Telefone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/CA_Telefonecomercial__c.field-meta.xml
<CustomField>
    <fullName>CA_Telefonecomercial__c</fullName>
    <description>Lista  - DDD (I) + TELEFONE</description>
    <label>Telefone Comercial</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/CA_TipoConta__c.field-meta.xml
<CustomField>
    <fullName>CA_TipoConta__c</fullName>
    <label>Tipo de Conta</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Proprietário</fullName>
            </value>
            <value>
                <fullName>Inquilino</fullName>
            </value>
            <value>
                <fullName>Fiador</fullName>
            </value>
            <value>
                <fullName>Representante</fullName>
            </value>
            <value>
                <fullName>Procurador</fullName>
            </value>
            <value>
                <fullName>Síndico</fullName>
            </value>
            <value>
                <fullName>Fornecedor</fullName>
            </value>
            <value>
                <fullName>Locatário Extra</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CA_Whatsapp__c.field-meta.xml
<CustomField>
    <fullName>CA_Whatsapp__c</fullName>
    <description>Lista  - DDD (I) + TELEFONE</description>
    <label>Whatsapp</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Case/fields/CA_Telefone__c.field-meta.xml
<CustomField>
    <fullName>CA_Telefone__c</fullName>
    <label>Telefone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Case/fields/CA_TelefoneComercial__c.field-meta.xml
<CustomField>
    <fullName>CA_TelefoneComercial__c</fullName>
    <label>Telefone Comercial</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Case/fields/CA_Whatsapp__c.field-meta.xml
<CustomField>
    <fullName>CA_Whatsapp__c</fullName>
    <label>Whatsapp</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Case/fields/Numero_de_Protocolo__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_Protocolo__c</fullName>
    <displayFormat>{YYYY}{MM}{DD}{0000}</displayFormat>
    <label>Número de Protocolo</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/classes/CardAccountAndCaseInfoController.cls
public with sharing class CardAccountAndCaseInfoController {

    @AuraEnabled(cacheable=true)
    public static Map<String, Object> getAccountAndCaseFromSession(Id sessionId) {
        if (sessionId == null) {
            return null;
        }
        
        if (!Schema.sObjectType.MessagingSession.isAccessible()) {
            throw new AuraHandledException('Você não tem permissão para acessar informações da sessão de mensagens.');
        } else if (!Schema.sObjectType.Case.isAccessible()) {
            throw new AuraHandledException('Você não tem permissão para acessar informações do caso.');
        } else {
        MessagingSession mSession = [
                SELECT
                    EndUserAccount.Id,
                    EndUserAccount.Name,
                    EndUserAccount.CA_TipoConta__c,
                    EndUserAccount.CA_Whatsapp__c,                    
                    EndUserAccount.CA_Telefone__c,
                    EndUserAccount.CA_Telefonecomercial__c,
                    EndUserAccount.CA_Email__c,
                    EndUserAccount.Owner.SmallPhotoUrl,
                    EndUserAccount.BillingAddress,
                    EndUserAccount.BillingCity,

                    Case.Id,
                    Case.CaseNumber,
                    Case.Subject,
                    Case.Status,
                    Case.Priority,
                    Case.Type,
                    Case.Origin,
                    Case.Numero_de_Protocolo__c,
                    Case.RecordTypeId

                FROM MessagingSession
                WHERE Id = :sessionId
                LIMIT 1
            ];

            //System.debug('Billingciy: ' + mSession.EndUserAccount.BillingCity);
            Map<String, Object> result = new Map<String, Object>();
            result.put('account', mSession.EndUserAccount);
            result.put('caseData', mSession.Case);

            return result;
        }        
    }

    @AuraEnabled
    public static void updateCaseRecord(Case caseToUpdate) {
        try {
            if (!Schema.sObjectType.Case.isUpdateable()) {
                throw new AuraHandledException('Você não tem permissão para atualizar Casos.');
            }
            
            update caseToUpdate;
            System.debug('caso atualizado: ' + caseToUpdate);
            
        } catch (Exception e) {
            throw new AuraHandledException('Erro ao atualizar: ' + e.getMessage());
        }
    }
}