force-app/main/default/objects/Account/fields/CA_Email__c.field-meta.xml
<CustomField>
    <fullName>CA_Email__c</fullName>
    <description>E-mail Principal</description>
    <label>E-mail</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/CA_Imovel__c.field-meta.xml
<CustomField>
    <fullName>CA_Imovel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Imovél</label>
    <referenceTo>CA_Imovel__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/CA_Telefone__c.field-meta.xml
<CustomField>
    <fullName>CA_Telefone__c</fullName>
    <description>Lista  - DDD (I) + TELEFONE</description>
    <label>Telefone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/CA_Telefonecomercial__c.field-meta.xml
<CustomField>
    <fullName>CA_Telefonecomercial__c</fullName>
    <description>Lista  - DDD (I) + TELEFONE</description>
    <label>Telefone Comercial</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/CA_Whatsapp__c.field-meta.xml
<CustomField>
    <fullName>CA_Whatsapp__c</fullName>
    <description>Lista  - DDD (I) + TELEFONE</description>
    <label>Whatsapp</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/CA_Imovel__c/CA_Imovel__c.object-meta.xml
<CustomObject>
    <label>Imóvel</label>
    <nameField>
        <label>Imóvel</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Imóveis</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CA_Imovel__c/fields/CA_ProprietarioImovel__c.field-meta.xml
<CustomField>
    <fullName>CA_ProprietarioImovel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proprietário Principal</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Imóveis (Proprietário Imóvel (Ajustado))</relationshipLabel>
    <relationshipName>Imoveis</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/CA_Imovel__c.field-meta.xml
<CustomField>
    <fullName>CA_Imovel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Imóvel</label>
    <referenceTo>CA_Imovel__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/CA_Telefone__c.field-meta.xml
<CustomField>
    <fullName>CA_Telefone__c</fullName>
    <label>Telefone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Case/fields/CA_TelefoneComercial__c.field-meta.xml
<CustomField>
    <fullName>CA_TelefoneComercial__c</fullName>
    <label>Telefone Comercial</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Case/fields/CA_Whatsapp__c.field-meta.xml
<CustomField>
    <fullName>CA_Whatsapp__c</fullName>
    <label>Whatsapp</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/CardCasePropertyInfoController.cls
public without sharing class CardCasePropertyInfoController {

    @AuraEnabled(cacheable=true)
    public static Account getPropertyOwnerFromCase(Id caseId) {
        if (caseId == null){
            return null;
        }

        Case c = [
            SELECT CA_Imovel__r.CA_ProprietarioImovel__r.Id,
                    CA_Imovel__r.CA_ProprietarioImovel__r.Name,
                    CA_Imovel__r.CA_ProprietarioImovel__r.Type,
                    CA_Imovel__r.CA_ProprietarioImovel__r.Phone,
                    CA_Imovel__r.CA_ProprietarioImovel__r.CA_Whatsapp__c,
                    CA_Imovel__r.CA_ProprietarioImovel__r.CA_Telefone__c,
                    CA_Imovel__r.CA_ProprietarioImovel__r.CA_Telefonecomercial__c,
                    CA_Imovel__r.CA_ProprietarioImovel__r.CA_Email__c,
                    CA_Imovel__r.CA_ProprietarioImovel__r.Owner.Id,
                    CA_Imovel__r.CA_ProprietarioImovel__r.Owner.Name,
                    CA_Imovel__r.CA_ProprietarioImovel__r.Owner.SmallPhotoUrl
            FROM Case
            WHERE Id = :caseId
            LIMIT 1
        ];

        return c.CA_Imovel__r.CA_ProprietarioImovel__r;
    }
}