force-app/main/default/objects/Account/fields/CA_Email__c.field-meta.xml
<CustomField>
    <fullName>CA_Email__c</fullName>
    <description>E-mail Principal</description>
    <label>E-mail</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/CA_Telefone__c.field-meta.xml
<CustomField>
    <fullName>CA_Telefone__c</fullName>
    <description>Lista  - DDD (I) + TELEFONE</description>
    <label>Telefone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/CA_Telefonecomercial__c.field-meta.xml
<CustomField>
    <fullName>CA_Telefonecomercial__c</fullName>
    <description>Lista  - DDD (I) + TELEFONE</description>
    <label>Telefone Comercial</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/CA_TipoConta__c.field-meta.xml
<CustomField>
    <fullName>CA_TipoConta__c</fullName>
    <label>Tipo de Conta</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Proprietário</fullName>
            </value>
            <value>
                <fullName>Inquilino</fullName>
            </value>
            <value>
                <fullName>Fiador</fullName>
            </value>
            <value>
                <fullName>Representante</fullName>
            </value>
            <value>
                <fullName>Procurador</fullName>
            </value>
            <value>
                <fullName>Síndico</fullName>
            </value>
            <value>
                <fullName>Fornecedor</fullName>
            </value>
            <value>
                <fullName>Locatário Extra</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CA_Whatsapp__c.field-meta.xml
<CustomField>
    <fullName>CA_Whatsapp__c</fullName>
    <description>Lista  - DDD (I) + TELEFONE</description>
    <label>Whatsapp</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Case/fields/CA_Telefone__c.field-meta.xml
<CustomField>
    <fullName>CA_Telefone__c</fullName>
    <label>Telefone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Case/fields/CA_TelefoneComercial__c.field-meta.xml
<CustomField>
    <fullName>CA_TelefoneComercial__c</fullName>
    <label>Telefone Comercial</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Case/fields/CA_Whatsapp__c.field-meta.xml
<CustomField>
    <fullName>CA_Whatsapp__c</fullName>
    <label>Whatsapp</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/CardAccountInfoController.cls
public without sharing class CardAccountInfoController {

    @AuraEnabled(cacheable=true)
    public static Account getAccountFromCase(Id caseId) {
        if (caseId == null) {
            return null;
        }
        
        if (!Schema.sObjectType.Account.isAccessible()) {
            throw new AuraHandledException('Você não tem permissão para acessar informações da conta.');
        } else if (!Schema.sObjectType.Case.isAccessible()) {
            throw new AuraHandledException('Você não tem permissão para acessar informações do caso.');
        } else {
            Case c = [
                SELECT Account.Id, Account.Name, Account.CA_TipoConta__c,
                    Account.CA_Whatsapp__c, Account.CA_Telefone__c, Account.CA_Telefonecomercial__c, Account.CA_Email__c,
                    Account.Owner.SmallPhotoUrl, Account.BillingAddress, Account.BillingCity
                FROM Case
                WHERE Id = :caseId
                LIMIT 1
            ];
            //System.debug('logLevel' + c.Account.BillingCity);
            return c.Account;
        }        
    }
}