force-app/main/default/objects/Protocolo__c/Protocolo__c.object-meta.xml
<CustomObject>
    <label>Protocolo</label>
    <nameField>
        <label>Protocolo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Protocolos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Protocolo__c/fields/CallSourceId__c.field-meta.xml
<CustomField>
    <fullName>CallSourceId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Campo usado para receber o Id da ligação quando o protocolo é gerado por uma ligação na 55BPX</description>
    <externalId>true</externalId>
    <label>Id da Ligacao</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Protocolo__c/fields/CallSourcePhone__c.field-meta.xml
<CustomField>
    <fullName>CallSourcePhone__c</fullName>
    <description>Campo utilizado para receber o telefone que gerou o protocolo, quando ele é criado por ligação pela 55BPX</description>
    <label>Telefone da Ligação</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Protocolo__c/fields/IdProtocolo__c.field-meta.xml
<CustomField>
    <fullName>IdProtocolo__c</fullName>
    <displayFormat>{YYYY}{MM}{DD}{0000}</displayFormat>
    <label>Protocol Id</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Protocolo__c/fields/ProtocolSource__c.field-meta.xml
<CustomField>
    <fullName>ProtocolSource__c</fullName>
    <label>Origem do Protocolo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Integração 55PBX</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Protocolo55PBXRepository.cls
public with sharing class Protocolo55PBXRepository {
    public void save(Protocolo__c protocolo) {
        upsert protocolo CallSourceId__c;
    }

    public Protocolo__c findById(Id salesforceId){
        if(salesforceId != null){
            return [SELECT Id, IdProtocolo__c, ProtocolSource__c, CallSourceId__c, CallSourcePhone__c
                FROM Protocolo__c
                WHERE Id = :salesforceId
            ];
        } else {
            throw new CalloutException('Não retornou salesforceId');
        }      
    }
}