force-app/main/default/objects/Protocolo__c/Protocolo__c.object-meta.xml
<CustomObject>
    <label>Protocolo</label>
    <nameField>
        <label>Protocolo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Protocolos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Protocolo__c/fields/IdProtocolo__c.field-meta.xml
<CustomField>
    <fullName>IdProtocolo__c</fullName>
    <displayFormat>{YYYY}{MM}{DD}{0000}</displayFormat>
    <label>Protocol Id</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/classes/Protocolo55PBXInboundAPI.cls
@RestResource(urlMapping='/55pbx/protocolos/*') //convenção REST usar S no fim!!@
global with sharing class Protocolo55PBXInboundAPI {
    global class ProtocoloResponse{
        public String protocolNumber;
        public String idSalesforce;
        public Boolean sucess;
        public String responseMessage;
    }
    global class ProtocoloRequest{
        public String idCall;
        public String phone;
    }

    @HttpPost //aqui usa o verbo corretoo
    global static ProtocoloResponse createProtocol(){
        RestRequest req = RestContext.request;
        ProtocoloResponse res = new ProtocoloResponse();

        try{
            String jsonBody = req.requestBody.toString();
            ProtocoloRequest reqData = (ProtocoloRequest) JSON.deserialize(jsonBody, ProtocoloRequest.class);

            if (reqData == null){
                throw new CalloutException('Body vazio. Precisa enviar o idCall e phone');
            }
            
            Protocolo__c createdProtocol = Protocolo55PBXService.processInboundProtocol(reqData.idCall, reqData.phone);
            
            res.protocolNumber = createdProtocol.IdProtocolo__c;
            res.idSalesforce = createdProtocol.Id;
            res.sucess = true;

        }catch (Exception e){
            res.sucess = false;
            res.responseMessage = e.getMessage();
        }
        return res;
    }
}